### ISSUE TITLE
Is this module compatible with the latest version of Humhub?

### ISSUE THREAD

**Issue by Ace2213** [GreenMeteor/humhub-freshdesk-module#4]
I'm running version 1.3.15

This module appears in ACP > Modules > Browse Online, but I'm unable to install it. 

Is it safe to install via GitHub or should I wait for the compatibility issues to be resolved?

![image](https://user-images.githubusercontent.com/12226710/64837957-6159e400-d5c7-11e9-96d5-13a5f1e4b1bd.png)

**Comment by ArchBlood** [comment]
The module itself does indeed work within the latest version of HumHub but would seem that the marketplace is seeing the max version which is set to [1.3](https://github.com/GreenMeteor/humhub-freshdesk-module/blob/master/module.json#L8) and doesn't render the versions under the `1.3.x` so will be looking into this so expect a new version of this and many other modules soon to fix this issue.
